version: '3.8'

services:
  # Backend API Server for Production
  backend:
    image: ${DOCKER_USERNAME}/finance-tracker-backend:latest
    container_name: finance-tracker-backend-prod
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App for Production
  frontend:
    image: ${DOCKER_USERNAME}/finance-tracker-frontend:latest
    container_name: finance-tracker-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
