version: 2

services:
  # Backend Service
  - type: web
    name: finance-tracker-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: finance-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        
  # Frontend Service  
  - type: web
    name: finance-tracker-frontend
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    buildCommand: |
      docker build \
        --build-arg REACT_APP_API_URL=https://finance-tracker-backend.onrender.com/api \
        -t finance-tracker-frontend .
        
databases:
  - name: finance-tracker-db
    databaseName: financetracker
    user: admin
